// ─────────────────────────────────────────────────────────────────────────────
//  CCNA Command Puzzle — Generated from Flackbox CCNA 200-301 Anki Deck
//  63 puzzles total
//  mode: "exec" = Router#    "config" = Router(config)#
// ─────────────────────────────────────────────────────────────────────────────

const PUZZLES = [
  {
    id: 1,
    scenario: 'This command is used to go to the Privileged Exec mode from the User Exec mode.',
    answer: 'enable',
    hint: 'Single word command: starts with \'e\'.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 2,
    scenario: 'This command makes the running configuration persistent across reboot.',
    answer: 'copy running-config startup-config',
    hint: 'Starts with \'copy running-config\' — 3 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 3,
    scenario: 'The \'show\' command that displays the entire running configuration on the router.',
    answer: 'show running-config',
    hint: 'Starts with \'show running-config\' — 2 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 4,
    scenario: 'What commands are entered on a router for it to be able to resolve hostnames?',
    answer: 'ip domain-lookup',
    hint: 'Starts with \'ip domain-lookup\' — 2 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 5,
    scenario: 'You are tasked to create a primary domain named \'flackbox.com\'. What command will you enter?',
    answer: 'ip domain-name flackbox.com',
    hint: 'Starts with \'ip domain-name\' — 3 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 6,
    scenario: 'What command is entered on a router for it to act as a DNS server?',
    answer: 'ip dns server',
    hint: 'Starts with \'ip dns\' — 3 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 7,
    scenario: 'What command is entered on the DNS-Client to allow it to send DNS queries to the DNS-Server?',
    answer: 'ip name-server 172.16.1.1',
    hint: 'Starts with \'ip name-server\' — 3 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 8,
    scenario: 'This command does a ping, hop by hop, from the source to the destination, and it will often indicate which router along the path has got the problem.',
    answer: 'traceroute',
    hint: 'Single word command: starts with \'t\'.',
    mode: 'exec',
    category: 'routing',
  },
  {
    id: 9,
    scenario: 'What command will you enter to configure the IP address 10.128.254.254/30 on an interface?',
    answer: 'ip address 10.128.254.254 255.255.255.252',
    hint: 'Starts with \'ip address\' — 4 words.',
    mode: 'config',
    category: 'interface',
  },
  {
    id: 10,
    scenario: 'What command will set the interface to full duplex?',
    answer: 'duplex full',
    hint: 'Starts with \'duplex full\' — 2 words.',
    mode: 'config',
    category: 'interface',
  },
  {
    id: 11,
    scenario: 'What command is entered on the interface level to configure a speed of 100 Mbps?',
    answer: 'speed 100',
    hint: 'Starts with \'speed 100\' — 2 words.',
    mode: 'config',
    category: 'interface',
  },
  {
    id: 12,
    scenario: 'This command enables auto duplex configuration.',
    answer: 'duplex auto',
    hint: 'Starts with \'duplex auto\' — 2 words.',
    mode: 'config',
    category: 'interface',
  },
  {
    id: 13,
    scenario: 'This command shows you the version of IOS that is running on the device. It will also show additional information like how much memory is installed in the device.',
    answer: 'show version',
    hint: 'Starts with \'show version\' — 2 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 14,
    scenario: 'This command enables IPv6 routing.',
    answer: 'ipv6 unicast-routing',
    hint: 'Starts with \'ipv6 unicast-routing\' — 2 words.',
    mode: 'config',
    category: 'ipv6',
  },
  {
    id: 15,
    scenario: 'What command is used to copy the running configuration to the TFTP server?',
    answer: 'copy running-config tftp',
    hint: 'Starts with \'copy running-config\' — 3 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 16,
    scenario: 'This command is used to copy the IOS image to the device\'s Flash using TFTP.',
    answer: 'copy tftp flash',
    hint: 'Starts with \'copy tftp\' — 3 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 17,
    scenario: 'This command disables logging to the console line.',
    answer: 'no logging console',
    hint: 'Starts with \'no logging\' — 3 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 18,
    scenario: 'This command causes the command prompt to be copied below any Syslog messages on the CLI, so you do not get interrupted in typing.',
    answer: 'logging synchronous',
    hint: 'Starts with \'logging synchronous\' — 2 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 19,
    scenario: 'This is the command to generate a digital certificate.',
    answer: 'crypto key generate rsa',
    hint: 'Starts with \'crypto key\' — 4 words.',
    mode: 'config',
    category: 'security',
  },
  {
    id: 20,
    scenario: 'This command shows all passwords in the running configuration in an encrypted form.',
    answer: 'service password-encryption',
    hint: 'Starts with \'service password-encryption\' — 2 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 21,
    scenario: 'You are tasked to enter an encrypted password of \'FlackboxPass0!\' for the Privileged Exec mode access. What command will you enter? R1(config)#',
    answer: 'enable secret flackboxpass0!',
    hint: 'Starts with \'enable secret\' — 3 words.',
    mode: 'exec',
    category: 'system',
  },
  {
    id: 22,
    scenario: 'This command configures a router to become an NTP server, even if it is not synchronized with other NTP sources.',
    answer: 'ntp master',
    hint: 'Starts with \'ntp master\' — 2 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 23,
    scenario: 'This command is used to remove all dynamic translations from the NAT translation table.',
    answer: 'clear ip nat translation *',
    hint: 'Starts with \'clear ip\' — 5 words.',
    mode: 'exec',
    category: 'nat',
  },
  {
    id: 24,
    scenario: 'You are tasked to create a NAT pool named \'FlackboxNAT\' with global address range of 100.1.2.3 to 100.1.2.10 and a subnet mask of /27. What commands will you enter? R1(config)# ?',
    answer: 'ip nat pool flackboxnat 100.1.2.3 100.1.2.10 netmask 255.255.255.224',
    hint: 'Starts with \'ip nat\' — 8 words.',
    mode: 'config',
    category: 'nat',
  },
  {
    id: 27,
    scenario: 'This show command shows the Inside Global, Inside Local, Outside Local, and Outside Global address translations.',
    answer: 'show ip nat translations',
    hint: 'Starts with \'show ip\' — 4 words.',
    mode: 'exec',
    category: 'nat',
  },
  {
    id: 28,
    scenario: 'This show command will output how many addresses have been translated by NAT.',
    answer: 'show ip nat statistics',
    hint: 'Starts with \'show ip\' — 4 words.',
    mode: 'exec',
    category: 'nat',
  },
  {
    id: 29,
    scenario: 'What command is used to disable automatic summarization?',
    answer: 'no auto-summary',
    hint: 'Starts with \'no auto-summary\' — 2 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 30,
    scenario: 'This show command is used to check EIGRP neighbor adjacency.',
    answer: 'show ip eigrp neighbors',
    hint: 'Starts with \'show ip\' — 4 words.',
    mode: 'exec',
    category: 'eigrp',
  },
  {
    id: 31,
    scenario: 'What command will you enter to manually specify an OSPF cost value of 15? R1(config-if)# ?',
    answer: 'ip ospf cost 15',
    hint: 'Starts with \'ip ospf\' — 4 words.',
    mode: 'config',
    category: 'ospf',
  },
  {
    id: 32,
    scenario: 'What is the show command used to view the routing table on a router?',
    answer: 'show ip route',
    hint: 'Starts with \'show ip\' — 3 words.',
    mode: 'exec',
    category: 'routing',
  },
  {
    id: 33,
    scenario: 'You are asked to configure a static route going to 172.16.0.0/16 with the next hop address of 172.17.1.1. What command will you enter? Router(config)# ?',
    answer: 'ip route 172.16.0.0 255.255.0.0 172.17.1.1',
    hint: 'Starts with \'ip route\' — 5 words.',
    mode: 'config',
    category: 'routing',
  },
  {
    id: 34,
    scenario: 'What command will you enter if you are asked to create an LACP port channel 10 in Active mode? Switch(config-if-range)# ?',
    answer: 'channel-group 10 mode active',
    hint: 'Starts with \'channel-group 10\' — 4 words.',
    mode: 'config',
    category: 'etherchannel',
  },
  {
    id: 35,
    scenario: 'What command will you enter if you are asked to create a PAgP port channel 5 in Desirable mode? Switch(config-if-range)# ?',
    answer: 'channel-group 5 mode desirable',
    hint: 'Starts with \'channel-group 5\' — 4 words.',
    mode: 'config',
    category: 'etherchannel',
  },
  {
    id: 36,
    scenario: 'What commands will you enter to configure a standard ACL with an access-list number of 10 and to allow traffic from 192.168.10.0/24? Router(config)# ?',
    answer: 'access-list 10 permit 192.168.10.0 0.0.0.255',
    hint: 'Starts with \'access-list 10\' — 5 words.',
    mode: 'config',
    category: 'security',
  },
  {
    id: 37,
    scenario: 'What commands are entered to configure a Standard ACL with access list number of 1 and will allow all traffic? Router(config)# ?',
    answer: 'access-list 1 permit any',
    hint: 'Starts with \'access-list 1\' — 4 words.',
    mode: 'config',
    category: 'security',
  },
  {
    id: 38,
    scenario: 'What command will you enter to configure an extended ACL for \'FlackboxACL\'? Router(config)# ?',
    answer: 'ip access-list extended flackboxacl',
    hint: 'Starts with \'ip access-list\' — 4 words.',
    mode: 'config',
    category: 'security',
  },
  {
    id: 39,
    scenario: 'With DHCP snooping, what command will you enter to make an interface a trusted port? Switch(config-if)# ?',
    answer: 'ip dhcp snooping trust',
    hint: 'Starts with \'ip dhcp\' — 4 words.',
    mode: 'config',
    category: 'dhcp',
  },
  {
    id: 40,
    scenario: 'What command will you enter to enable DAI on VLAN 100? Switch(config)# ?',
    answer: 'ip arp inspection vlan 100',
    hint: 'Starts with \'ip arp\' — 5 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 41,
    scenario: 'This show command is used to verify the port security addresses.',
    answer: 'show port-security address',
    hint: 'Starts with \'show port-security\' — 3 words.',
    mode: 'exec',
    category: 'security',
  },
  {
    id: 42,
    scenario: 'What command will you enter to set the maximum number of MAC addresses allowed to send traffic into the interface to 5? Switch(config-if)# ?',
    answer: 'switchport port-security maximum 5',
    hint: 'Starts with \'switchport port-security\' — 4 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 43,
    scenario: 'This show command will show what the virtual IP address is, the state, and the virtual MAC address.',
    answer: 'show standby',
    hint: 'Starts with \'show standby\' — 2 words.',
    mode: 'exec',
    category: 'fhrp',
  },
  {
    id: 44,
    scenario: 'What command will you enter to configure a VIP of 172.16.1.1 with HSRP group number 1? Router(config-if)# ?',
    answer: 'standby 1 ip 172.16.1.1',
    hint: 'Starts with \'standby 1\' — 4 words.',
    mode: 'config',
    category: 'fhrp',
  },
  {
    id: 45,
    scenario: 'What command is entered to configure a priority of 50 on HSRP group 10? Router(config-if)# ?',
    answer: 'standby 10 priority 50',
    hint: 'Starts with \'standby 10\' — 4 words.',
    mode: 'config',
    category: 'fhrp',
  },
  {
    id: 46,
    scenario: 'What command is entered to enable pre-emption on HSRP group 10? Router(config-if)# ?',
    answer: 'standby 10 preempt',
    hint: 'Starts with \'standby 10\' — 3 words.',
    mode: 'config',
    category: 'fhrp',
  },
  {
    id: 47,
    scenario: 'What show command is used to get information about the DHCP lease?',
    answer: 'show dhcp lease',
    hint: 'Starts with \'show dhcp\' — 3 words.',
    mode: 'exec',
    category: 'dhcp',
  },
  {
    id: 48,
    scenario: 'What command is entered to make a Cisco router a DHCP client? Router(config-if)# ?',
    answer: 'ip address dhcp',
    hint: 'Starts with \'ip address\' — 3 words.',
    mode: 'config',
    category: 'dhcp',
  },
  {
    id: 49,
    scenario: 'What command is entered so that the router interface will be able to forward DHCP requests to the external DHCP server at 172.100.10.1? Router(config-if)# ?',
    answer: 'ip helper-address 172.100.10.1',
    hint: 'Starts with \'ip helper-address\' — 3 words.',
    mode: 'config',
    category: 'system',
  },
  {
    id: 50,
    scenario: 'You are tasked to create a DHCP pool named \'Flackbox\', what command will you enter? Router(config)# ?',
    answer: 'ip dhcp pool flackbox',
    hint: 'Starts with \'ip dhcp\' — 4 words.',
    mode: 'config',
    category: 'dhcp',
  },
  {
    id: 51,
    scenario: 'To see the addresses that were given out by the DHCP server and who they were given out to, this show command is used.',
    answer: 'show ip dhcp binding',
    hint: 'Starts with \'show ip\' — 4 words.',
    mode: 'exec',
    category: 'dhcp',
  },
  {
    id: 52,
    scenario: 'What is the configuration to disable DTP? Switch(config-if)#',
    answer: 'switchport nonegotiate',
    hint: 'Starts with \'switchport nonegotiate\' — 2 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 54,
    scenario: 'What command will you enter to allow VLANs 50 and 120 only on the trunk port? Switch(config-if)# ?',
    answer: 'switchport trunk allowed vlan 50,120',
    hint: 'Starts with \'switchport trunk\' — 5 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 55,
    scenario: 'What command is used to configure an interface as an access port? Switch(config-if)# ?',
    answer: 'switchport mode access',
    hint: 'Starts with \'switchport mode\' — 3 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 57,
    scenario: 'What command will set all ports to Portfast by default? Switch(config)# ?',
    answer: 'spanning-tree portfast default',
    hint: 'Starts with \'spanning-tree portfast\' — 3 words.',
    mode: 'config',
    category: 'stp',
  },
  {
    id: 58,
    scenario: 'What command will enable BPDU Guard on an interface? Switch(config-if)# ?',
    answer: 'spanning-tree bpduguard enable',
    hint: 'Starts with \'spanning-tree bpduguard\' — 3 words.',
    mode: 'config',
    category: 'stp',
  },
  {
    id: 59,
    scenario: 'To configure Root Guard on an interface, what command is used? Switch(config-if)# ?',
    answer: 'spanning-tree guard root',
    hint: 'Starts with \'spanning-tree guard\' — 3 words.',
    mode: 'config',
    category: 'stp',
  },
  {
    id: 60,
    scenario: 'What command will you enter on a switch for it to become the Root Bridge for VLAN 10? Switch(config)# ?',
    answer: 'spanning-tree vlan 10 root primary',
    hint: 'Starts with \'spanning-tree vlan\' — 5 words.',
    mode: 'config',
    category: 'vlan',
  },
  {
    id: 61,
    scenario: 'What command will allow you to create a sub-interface with a number of 15 on Fast Ethernet 0/5? Router(config)# ?',
    answer: 'interface fastethernet 0/5.15',
    hint: 'Starts with \'interface fastethernet\' — 3 words.',
    mode: 'config',
    category: 'interface',
  },
  {
    id: 62,
    scenario: 'This command enables IP routing on a Layer 3 switch. Switch(config)# ?',
    answer: 'ip routing',
    hint: 'Starts with \'ip routing\' — 2 words.',
    mode: 'config',
    category: 'routing',
  },
  {
    id: 63,
    scenario: 'This command allows a Layer 3 switch physical interface to act like a router port. Switch(config-if)# ?',
    answer: 'no switchport',
    hint: 'Starts with \'no switchport\' — 2 words.',
    mode: 'config',
    category: 'vlan',
  }
];
